Repository opentensor/bittensor, pull requests merged in 2022-10, with the labels that each got.

#927 Release/3.3.4
  .circleci/config.yml
  CONTRIBUTING.md
  DEVELOPMENT_WORKFLOW.md
  README.md
  VERSION
  bittensor/__init__.py
  bittensor/_axon/__init__.py
  bittensor/_axon/axon_impl.py
  bittensor/_cli/__init__.py
  bittensor/_cli/cli_impl.py
  bittensor/_config/config_impl.py
  bittensor/_dendrite/__init__.py
  bittensor/_neuron/text/core_server/nucleus_impl.py
  bittensor/_neuron/text/core_server/run.py
  bittensor/_neuron/text/core_validator/__init__.py
  bittensor/_subtensor/__init__.py
  bittensor/_subtensor/subtensor_impl.py
  bittensor/_wallet/wallet_impl.py
  bittensor/utils/__init__.py
  bittensor/utils/balance.py
  bittensor/utils/register_cuda.py
  bittensor/utils/tokenizer_utils.py
  scripts/update_version.sh
  setup.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_dataset.py
  tests/integration_tests/test_dataset_ipfs.py
  tests/integration_tests/test_dendrite.py
  tests/integration_tests/test_subtensor.py
  tests/unit_tests/benchmarking/test_dendrite_multiprocess.py
  tests/unit_tests/bittensor_tests/test_axon.py
  tests/unit_tests/bittensor_tests/test_balance.py
  tests/unit_tests/bittensor_tests/test_config.py
  tests/unit_tests/bittensor_tests/test_forward_backward.py
  tests/unit_tests/bittensor_tests/test_neuron.py
  tests/unit_tests/bittensor_tests/test_receptor.py
  tests/unit_tests/bittensor_tests/test_receptor_pool.py
  tests/unit_tests/bittensor_tests/test_subtensor.py
  tests/unit_tests/bittensor_tests/test_wallet.py
  tests/unit_tests/bittensor_tests/utils/test_tokenizer_utils.py
  tests/unit_tests/bittensor_tests/utils/test_utils.py
Labels: RELEASE

#928 feature/BIT-579/Adding Prometheus
  bittensor/__init__.py
  bittensor/_axon/__init__.py
  bittensor/_axon/axon_impl.py
  bittensor/_config/__init__.py
  bittensor/_config/config_impl.py
  bittensor/_dendrite/__init__.py
  bittensor/_dendrite/dendrite_impl.py
  bittensor/_neuron/text/core_server/__init__.py
  bittensor/_neuron/text/core_server/nucleus_impl.py
  bittensor/_neuron/text/core_server/run.py
  bittensor/_neuron/text/core_validator/__init__.py
  bittensor/_prometheus/__init__.py
  requirements.txt
  tests/integration_tests/test_prometheus.py
  tests/unit_tests/bittensor_tests/test_neuron.py
Labels: enhancement

#937 [Fix] only reregister if flag is set
  bittensor/_cli/cli_impl.py
  bittensor/_config/__init__.py
  bittensor/_wallet/__init__.py
  tests/integration_tests/test_cli.py
Labels: bug

#951 [Fix] Fix declare of variable
  bittensor/utils/__init__.py
Labels: bug

#943 Release/3.4.0
  README.md
  VERSION
  bittensor/__init__.py
  bittensor/_axon/__init__.py
  bittensor/_axon/axon_impl.py
  bittensor/_cli/__init__.py
  bittensor/_cli/cli_impl.py
  bittensor/_config/__init__.py
  bittensor/_config/config_impl.py
  bittensor/_dendrite/__init__.py
  bittensor/_dendrite/dendrite_impl.py
  bittensor/_neuron/text/core_server/__init__.py
  bittensor/_neuron/text/core_server/nucleus_impl.py
  bittensor/_neuron/text/core_server/run.py
  bittensor/_neuron/text/core_validator/__init__.py
  bittensor/_prometheus/__init__.py
  bittensor/_subtensor/__init__.py
  bittensor/_subtensor/subtensor_impl.py
  bittensor/_subtensor/subtensor_mock.py
  bittensor/_wallet/__init__.py
  bittensor/_wallet/wallet_impl.py
  bittensor/utils/__init__.py
  bittensor/utils/weight_utils.py
  requirements.txt
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_prometheus.py
  tests/integration_tests/test_subtensor.py
  tests/unit_tests/bittensor_tests/test_neuron.py
  tests/unit_tests/bittensor_tests/test_wallet.py
  tests/unit_tests/bittensor_tests/utils/test_utils.py
  tests/unit_tests/bittensor_tests/utils/test_weight_utils.py
Labels: RELEASE

#954 [Hotfix] Fix CUDA Reg update block
  bittensor/__init__.py
  bittensor/utils/__init__.py
  tests/unit_tests/bittensor_tests/utils/test_utils.py
Labels: bug

#958 [Fix] stake conversion issue
  bittensor/_cli/cli_impl.py
  bittensor/_subtensor/subtensor_impl.py
  bittensor/utils/balance.py
  tests/integration_tests/test_cli.py
  tests/unit_tests/bittensor_tests/test_balance.py
  tests/unit_tests/bittensor_tests/test_subtensor.py
Labels: bug
