Repository opentensor/bittensor, pull requests merged in 2022-12, with the labels that each got.

#1020 Fixes issue with --neuron.no_set_weights
  bittensor/_neuron/text/core_server/run.py
Labels: bug, release/3.6.0

#996 [Fix] fix max stake for single
  bittensor/_cli/cli_impl.py
  tests/integration_tests/test_cli.py
Labels: release/3.6.0

#995 [Feature] mention balance if not no prompt
  bittensor/_cli/__init__.py
Labels: enhancement, feature, task, release/3.6.0

#983 Add signature v2 format
  bittensor/__init__.py
  bittensor/_axon/__init__.py
  bittensor/_receptor/receptor_impl.py
  bittensor/_subtensor/subtensor_impl.py
  tests/unit_tests/bittensor_tests/test_axon.py
  tests/unit_tests/bittensor_tests/test_forward_backward.py
  tests/unit_tests/bittensor_tests/test_receptor.py
Labels: enhancement, feature, release/3.6.0

#1022 [BIT-601] Scaling law on EMA loss
  bittensor/_neuron/text/core_validator/__init__.py
  bittensor/_subtensor/subtensor_impl.py
Labels: release/3.6.0

#1027 [BIT-602] Update scaling power from subtensor
  bittensor/_neuron/text/core_validator/__init__.py
Labels: release/3.6.0

#1023 Release 3.6.0
  .circleci/config.yml
  .github/workflows/docker_image_push.yml
  CHANGELOG.md
  Makefile
  VERSION
  bittensor/__init__.py
  bittensor/_axon/__init__.py
  bittensor/_cli/__init__.py
  bittensor/_cli/cli_impl.py
  bittensor/_dendrite/__init__.py
  bittensor/_neuron/text/core_server/run.py
  bittensor/_neuron/text/core_validator/__init__.py
  bittensor/_receptor/receptor_impl.py
  bittensor/_subtensor/subtensor_impl.py
  requirements.txt
  requirements/cubit.txt
  requirements/dev.txt
  requirements/prod.txt
  scripts/release/release.sh
  setup.py
  tests/integration_tests/test_cli.py
  tests/integration_tests/test_dendrite.py
  tests/unit_tests/bittensor_tests/test_axon.py
  tests/unit_tests/bittensor_tests/test_forward_backward.py
  tests/unit_tests/bittensor_tests/test_receptor.py
Labels: release/3.6.0, release-branch
