Repository opentensor/bittensor, pull requests merged in 2025-02, with the labels that each got.

#2618 Use async-substrate-interface for runtime decoding
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/__init__.py
  bittensor/core/chain_data/axon_info.py
  bittensor/core/chain_data/delegate_info.py
  bittensor/core/chain_data/delegate_info_lite.py
  bittensor/core/chain_data/dynamic_info.py
  bittensor/core/chain_data/info_base.py
  bittensor/core/chain_data/ip_info.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/chain_data/neuron_certificate.py
  bittensor/core/chain_data/neuron_info.py
  bittensor/core/chain_data/neuron_info_lite.py
  bittensor/core/chain_data/prometheus_info.py
  bittensor/core/chain_data/scheduled_coldkey_swap_info.py
  bittensor/core/chain_data/stake_info.py
  bittensor/core/chain_data/subnet_hyperparameters.py
  bittensor/core/chain_data/subnet_info.py
  bittensor/core/chain_data/subnet_state.py
  bittensor/core/chain_data/utils.py
  bittensor/core/metagraph.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/utils/mock/subtensor_mock.py
  requirements/prod.txt
  tests/helpers/integration_websocket_data.py
  tests/helpers/registry
  tests/integration_tests/test_metagraph_integration.py
  tests/integration_tests/test_subtensor_integration.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: do not merge, rao

#2622 Fixes, adds stake and other methods
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: async migration

#2624 Add `subnet_volume` field to `MetagraphInfo` and `DynamicInfo`
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/dynamic_info.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/metagraph.py
  bittensor/core/subtensor.py
  requirements/prod.txt
  tests/e2e_tests/conftest.py
  tests/helpers/integration_websocket_data.py
  tests/unit_tests/test_async_subtensor.py
Labels: rao

#2637 Bug fixes after release SDK v9.0.0rc1
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/subnet_state.py
  bittensor/core/subtensor.py
  tests/unit_tests/test_async_subtensor.py
Labels: bug, enhancement, rao

#2642 Bringing meta fields to a common form with float values float(TAO) instead of Balance and Tensor
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/metagraph.py
  requirements/dev.txt
  tests/unit_tests/test_metagraph.py
Labels: bug, rao

#2647 Fix for extra fields from chain data
  bittensor/core/chain_data/info_base.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/metagraph.py
  bittensor/utils/balance.py
Labels: bug

#2655 feat/roman/deps
  requirements/dev.txt
  requirements/prod.txt
  setup.py
Labels: rao

#2670 Update deps and default network/endpoint
  bittensor/core/settings.py
  requirements/prod.txt
  tests/unit_tests/test_async_subtensor.py
Labels: rao

#2674 fix e2e test incentive
  tests/e2e_tests/test_incentive.py
Labels: testing

#2686 Release/9.0.1
  CHANGELOG.md
  VERSION
  bittensor/core/async_subtensor.py
  bittensor/core/axon.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/metagraph.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/utils/balance.py
  bittensor/utils/btlogging/loggingmachine.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_neuron_certificate.py
  tests/unit_tests/conftest.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_weights.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_axon.py
  tests/unit_tests/test_dendrite.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/utils/test_networking.py
Labels: Release

#2712 Release/9.0.3
  CHANGELOG.md
  VERSION
  bittensor/core/async_subtensor.py
  bittensor/core/dendrite.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  scripts/install.sh
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_commitment.py
  tests/e2e_tests/test_cross_subtensor_compatibility.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_config.py
  tests/unit_tests/test_dendrite.py
  tests/unit_tests/test_subtensor.py
Labels: Release

#2714 improve `wait_for_node_start` until 20 mins
  tests/e2e_tests/conftest.py
Labels: enhancement, testing
