Repository opentensor/bittensor, pull requests merged in 2025-01, with the labels that each got.

#2565 [SDK] Get rid of py-substrate-interface (DO NOT MERGE)
  bittensor/__init__.py
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/__init__.py
  bittensor/core/chain_data/neuron_info.py
  bittensor/core/chain_data/weight_commit_info.py
  bittensor/core/dendrite.py
  bittensor/core/extrinsics/async_commit_reveal.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/registration.py
  bittensor/core/extrinsics/asyncex/root.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/commit_weights.py
  bittensor/core/extrinsics/registration.py
  bittensor/core/extrinsics/root.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/metagraph.py
  bittensor/core/subtensor.py
  bittensor/core/types.py
  bittensor/utils/__init__.py
  bittensor/utils/delegates_details.py
  bittensor/utils/mock/subtensor_mock.py
  bittensor/utils/substrate_interface.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_root_set_weights.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/integration_tests/test_metagraph_integration.py
  tests/unit_tests/extrinsics/__init__.py
  tests/unit_tests/extrinsics/asyncex/__init__.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/asyncex/test_registration.py
  tests/unit_tests/extrinsics/asyncex/test_root.py
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/asyncex/test_weights.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_weights.py
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/extrinsics/test_root.py
  tests/unit_tests/extrinsics/test_serving.py
  tests/unit_tests/extrinsics/test_set_weights.py
  tests/unit_tests/extrinsics/test_staking.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/extrinsics/test_unstaking.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_metagraph.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/utils/test_async_substrate_interface.py
Labels: enhancement, bittensor, do not merge, async migration

#2572 Uses the new async_substrate_interface lib
  bittensor/core/async_subtensor.py
  bittensor/core/errors.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  bittensor/utils/mock/subtensor_mock.py
  bittensor/utils/substrate_interface.py
  requirements/prod.txt
  setup.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/integration_tests/old_test_subtensor_integration.py
  tests/unit_tests/extrinsics/test_utils.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/utils/test_async_substrate_interface.py
Labels: async migration

#2540 Updates tests for btwallet 3.0.0
  .github/workflows/e2e-subtensor-tests.yaml
  bittensor/core/subtensor.py
  requirements/prod.txt
  tests/e2e_tests/test_transfer.py
  tests/integration_tests/utils/test_init.py
  tests/unit_tests/test_config.py
  tests/unit_tests/test_subtensor.py
Labels: do not merge

#2599 Make code as beautiful as it has never been before
  bittensor/__init__.py
  bittensor/__main__.py
  bittensor/core/axon.py
  bittensor/core/chain_data/axon_info.py
  bittensor/core/chain_data/neuron_info.py
  bittensor/core/chain_data/subnet_hyperparameters.py
  bittensor/core/config.py
  bittensor/core/dendrite.py
  bittensor/core/extrinsics/__init__.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/registration.py
  bittensor/core/extrinsics/asyncex/root.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/metagraph.py
  bittensor/core/settings.py
  bittensor/core/stream.py
  bittensor/core/synapse.py
  bittensor/core/tensor.py
  bittensor/core/types.py
  bittensor/utils/axon_utils.py
  bittensor/utils/balance.py
  bittensor/utils/btlogging/__init__.py
  bittensor/utils/btlogging/console.py
  bittensor/utils/btlogging/defines.py
  bittensor/utils/btlogging/format.py
  bittensor/utils/btlogging/helpers.py
  bittensor/utils/btlogging/loggingmachine.py
  bittensor/utils/deprecated.py
  bittensor/utils/formatting.py
  bittensor/utils/mock/__init__.py
  bittensor/utils/networking.py
  bittensor/utils/registration.py
  bittensor/utils/registration/async_pow.py
  bittensor/utils/registration/pow.py
  bittensor/utils/registration/register_cuda.py
  bittensor/utils/subnets.py
  bittensor/utils/substrate_utils/hasher.py
  bittensor/utils/substrate_utils/storage.py
  bittensor/utils/version.py
  bittensor/utils/weight_utils.py
  setup.py
  tests/__init__.py
  tests/helpers/__init__.py
  tests/helpers/helpers.py
  tests/integration_tests/__init__.py
  tests/integration_tests/test_metagraph_integration.py
  tests/unit_tests/test_axon.py
  tests/unit_tests/test_chain_data.py
  tests/unit_tests/test_dendrite.py
  tests/unit_tests/test_deprecated.py
  tests/unit_tests/test_synapse.py
  tests/unit_tests/test_tensor.py
  tests/unit_tests/utils/test_formatting.py
  tests/unit_tests/utils/test_registration.py
  tests/unit_tests/utils/test_utils.py
  tests/unit_tests/utils/test_version.py
  tests/unit_tests/utils/test_weight_utils.py
Labels: refactoring

#2579 YAASO: Yet Another AsyncSubtensor Overhaul
  bittensor/core/async_subtensor.py
  bittensor/core/axon.py
  bittensor/core/chain_data/axon_info.py
  bittensor/core/dendrite.py
  bittensor/core/errors.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/registration.py
  bittensor/core/extrinsics/asyncex/root.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/commit_weights.py
  bittensor/core/extrinsics/registration.py
  bittensor/core/extrinsics/root.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/metagraph.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/core/types.py
  bittensor/utils/__init__.py
  bittensor/utils/mock/subtensor_mock.py
  bittensor/utils/networking.py
  bittensor/utils/registration/__init__.py
  bittensor/utils/registration/async_pow.py
  bittensor/utils/registration/pow.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_root_set_weights.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/helpers/helpers.py
  tests/helpers/integration_websocket_data.py
  tests/integration_tests/test_metagraph_integration.py
  tests/integration_tests/test_subtensor_integration.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/asyncex/test_registration.py
  tests/unit_tests/extrinsics/asyncex/test_root.py
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/asyncex/test_weights.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_weights.py
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/extrinsics/test_root.py
  tests/unit_tests/extrinsics/test_serving.py
  tests/unit_tests/extrinsics/test_set_weights.py
  tests/unit_tests/extrinsics/test_staking.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/extrinsics/test_unstaking.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_axon.py
  tests/unit_tests/test_chain_data.py
  tests/unit_tests/test_metagraph.py
  tests/unit_tests/test_subtensor.py
Labels: do not merge, async migration

#2606 Add alias for `Subtensor.commit` as `set_commitment`
  bittensor/core/subtensor.py
Labels: rao

#2605 [RAO] Add methods to fetch metagraph data from the chain
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/__init__.py
  bittensor/core/chain_data/chain_identity.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/chain_data/utils.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/utils/balance.py
  requirements/dev.txt
  tests/unit_tests/test_async_subtensor.py
Labels: rao

#2607 Rewrite config.py
  bittensor/core/config.py
  requirements/dev.txt
Labels: enhancement, do not merge, refactoring

#2611 Update metagraph class with `rao` stuff
  bittensor/core/chain_data/subnet_state.py
  bittensor/core/metagraph.py
Labels: rao

#2612 [RAO] fix for unit test + refactoring
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/move_stake.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/metagraph.py
  bittensor/core/subtensor.py
  bittensor/utils/balance.py
  requirements/prod.txt
  tests/integration_tests/test_metagraph_integration.py
  tests/unit_tests/extrinsics/test_staking.py
  tests/unit_tests/extrinsics/test_unstaking.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_metagraph.py
  tests/unit_tests/test_subtensor.py
Labels: rao

#2613 fix integration metagraph test
  tests/helpers/integration_websocket_data.py
  tests/unit_tests/test_async_subtensor.py
Labels: testing, rao

#2619 Many small fixes
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/dynamic_info.py
  bittensor/core/chain_data/stake_info.py
  bittensor/core/metagraph.py
  bittensor/core/subtensor.py
  bittensor/core/types.py
  bittensor/utils/__init__.py
  bittensor/utils/balance.py
  bittensor/utils/delegates_details.py
  bittensor/utils/networking.py
  bittensor/utils/substrate_utils/storage.py
Labels: enhancement
