Repository opentensor/bittensor, pull requests merged in 2025-04, with the labels that each got.

#2766 Add get_owned_hotkeys to subtensor and async one + tests
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature

#2781 Add drand-commitments
  .circleci/config.yml
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/utils.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/subtensor.py
  requirements/prod.txt
  tests/e2e_tests/test_reveal_commitements.py
Labels: feature, testing

#2785 Missing f-string format
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/set_weights.py
Labels: bug

#2786 bump version
  bittensor/core/axon.py
  pyproject.toml
  requirements/prod.txt
Labels: bug

#2787 Improvement and fix for https://github.com/opentensor/bittensor/pull/2781
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/utils.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_reveal_commitements.py
Labels: bug, enhancement

#2790 Add `stop_existing_test_containers` logic before run e2e test/s
  tests/e2e_tests/conftest.py
Labels: enhancement

#2788 Bump async substrate interface
  pyproject.toml
Labels: do not merge

#2791 Improve CRv3 functionality
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/test_subtensor.py
Labels: enhancement, testing

#2764 Improve logic in Balance magic methods
  bittensor/utils/balance.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/utils/chain_interactions.py
Labels: bug, feature

#2805 Release/9.3.0
  .circleci/config.yml
  .github/workflows/e2e-subtensor-tests.yaml
  CHANGELOG.md
  README.md
  VERSION
  bittensor/__main__.py
  bittensor/core/async_subtensor.py
  bittensor/core/axon.py
  bittensor/core/chain_data/proposal_vote_data.py
  bittensor/core/chain_data/utils.py
  bittensor/core/errors.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  bittensor/utils/balance.py
  bittensor/utils/easy_imports.py
  bittensor/utils/registration/pow.py
  bittensor/utils/version.py
  bittensor/utils/weight_utils.py
  pyproject.toml
  requirements/prod.txt
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_commitment.py
  tests/e2e_tests/test_delegate.py
  tests/e2e_tests/test_dendrite.py
  tests/e2e_tests/test_hotkeys.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_reveal_commitements.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
Labels: Release

#2795 Fix for flaky behavior of `test_incentive`, `test_commit_weights` and `test_set_weights`
  .github/workflows/e2e-subtensor-tests.yaml
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  pyproject.toml
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/extrinsics/asyncex/test_weights.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: testing

#2808 Add `get_next_epoch_start_block` method to Async/Subtensor
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
Labels: feature

#2811 Adds compatibility for torch 2.6.0+
  bittensor/core/metagraph.py
  pyproject.toml
  requirements/torch.txt
Labels: enhancement

#2809 docs: replaced discord link with documentation
  README.md
Labels: documentation

#2816 sometimes it's still flaky because the chain returns data with time offset
  tests/e2e_tests/test_commit_reveal_v3.py
Labels: bug, testing

#2820 Update CONTRIBUTING hyperlinks
  contrib/CONTRIBUTING.md
Labels: documentation

#2826 fix/roman/get-metagraph-identities
  bittensor/core/chain_data/metagraph_info.py
  tests/e2e_tests/test_metagraph.py
  tests/unit_tests/chain_data/__init__.py
  tests/unit_tests/chain_data/test_metagraph_info.py
Labels: bug

#2827 Replace waiting logic for `test_commit_reveal_v3.py`
  tests/e2e_tests/test_commit_reveal_v3.py
Labels: bug, testing

#2828 Add `start_call` extrinsic to the sdk
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/start_call.py
  bittensor/core/extrinsics/start_call.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_incentive.py
  tests/unit_tests/extrinsics/asyncex/test_start_call.py
  tests/unit_tests/extrinsics/test_start_call.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature

#2824 Add `timelock` module
  bittensor/core/timelock.py
  bittensor/utils/easy_imports.py
  pyproject.toml
  tests/integration_tests/test_timelock.py
Labels: feature

#2771 Fix: raise_error=True in AsyncSubtensor fails to get error_message
  bittensor/core/async_subtensor.py
  tests/unit_tests/test_async_subtensor.py
Labels: bug

#2772 Fix: async set_subnet_identity_extrinsic doesn't sign the extrinsic
  bittensor/core/extrinsics/asyncex/registration.py
  tests/unit_tests/extrinsics/asyncex/test_registration.py
Labels: bug

#2831 Bumping ruff version
  bittensor/core/async_subtensor.py
  bittensor/core/axon.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/subtensor.py
  bittensor/core/threadpool.py
  pyproject.toml
  tests/e2e_tests/test_axon.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_dendrite.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_liquid_alpha.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_neuron_certificate.py
  tests/e2e_tests/test_reveal_commitements.py
  tests/e2e_tests/test_set_subnet_identity_extrinsic.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/test_stake_fee.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/test_subtensor_functions.py
  tests/e2e_tests/test_transfer.py
  tests/integration_tests/test_metagraph_integration.py
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/extrinsics/test_serving.py
  tests/unit_tests/extrinsics/test_set_weights.py
  tests/unit_tests/test_axon.py
  tests/unit_tests/test_metagraph.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/utils/test_balance.py
Labels: testing

#2830 Fix and improve e2e tests after `start call` new limit in subtensor
  .circleci/config.yml
  .github/workflows/e2e-subtensor-tests.yaml
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/start_call.py
  bittensor/core/extrinsics/start_call.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commitment.py
  tests/e2e_tests/test_delegate.py
  tests/e2e_tests/test_dendrite.py
  tests/e2e_tests/test_hotkeys.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_reveal_commitments.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/test_subtensor_functions.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/pytest.ini
Labels: bug, feature, testing

#2833 Add `bittensor.timelock` module description
  bittensor/core/timelock.py
Labels: documentation

#2818 fix: Update broken link in `CONTRIBUTING.md`
  contrib/CONTRIBUTING.md
Labels: documentation

#2834 remove `rao` endpoint from settings
  bittensor/core/settings.py
Labels: bug

#2839 Add `force_register_neuron` into MockSubtensor
  bittensor/utils/mock/subtensor_mock.py
  tests/integration_tests/test_metagraph_integration.py
  tests/integration_tests/test_subtensor_integration.py
Labels: bug, testing

#2842 Add `Monitor-Requirements-Size` workflow
  .github/workflows/monitor_requirements_size_master.yml
Labels: enhancement

#2846 Add `SelectiveMetagraph` interface into SDK
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/__init__.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_metagraph.py
  tests/integration_tests/test_subtensor_integration.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature, testing

#2849 Add one more attempt to e2e tests
  .github/workflows/e2e-subtensor-tests.yaml
  tests/e2e_tests/test_staking.py
Labels: testing

#2835 Add bittensor-drand==0.5.0
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/subtensor.py
  bittensor/core/timelock.py
  pyproject.toml
Labels: enhancement

#2852 Extend selective metagraph logic
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/utils/easy_imports.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: enhancement

#2854 Add methods to Async/Subtensor class
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature, testing
