Repository opentensor/bittensor, pull requests merged in 2025-09, with the labels that each got.

#3044 Fix bug if `block==0`
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/utils/mock/subtensor_mock.py
Labels: bug

#3049 Release/9.10.1
  CHANGELOG.md
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/utils/mock/subtensor_mock.py
  contrib/CONTRIBUTING.md
  pyproject.toml
Labels: Release

#3047 Improve e2e workflow
  .github/workflows/_run-e2e-single.yaml
  .github/workflows/compatibility.yml
  .github/workflows/e2e-subtensor-tests.yaml
  .github/workflows/flake8-and-mypy.yml
  .github/workflows/monitor_requirements_size_master.yml
  .github/workflows/nightly-e2e-tests-subtensor-main.yml
  .github/workflows/unit-and-integration-tests.yml
Labels: do not merge, testing

#3041 Fix broken links in CONTRIBUTING.md
  contrib/CONTRIBUTING.md
Labels: documentation

#3055 add commitments data into metagraph
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/chain_data/utils.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_subtensor_functions.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature

#3059 add getting OwnerHyperparamRateLimit in e2e test
  tests/e2e_tests/test_liquid_alpha.py
Labels: testing

#3056 `Subnet Mechanism` logic
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/errors.py
  bittensor/core/extrinsics/asyncex/children.py
  bittensor/core/extrinsics/asyncex/mechanism.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/sudo.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/utils.py
  bittensor/core/extrinsics/children.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/commit_weights.py
  bittensor/core/extrinsics/mechanism.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/sudo.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/metagraph.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/chain.py
  bittensor/core/subtensor_api/subnets.py
  bittensor/core/subtensor_api/utils.py
  bittensor/core/types.py
  bittensor/utils/__init__.py
  bittensor/utils/easy_imports.py
  bittensor/utils/weight_utils.py
  tests/e2e_tests/test_commit_reveal.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_hotkeys.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_liquid_alpha.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/test_subtensor_functions.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/extrinsics/asyncex/test_sub_subnet.py
  tests/unit_tests/extrinsics/test_sub_subnet.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature, subtensor-localnet:testnet

#3068 bumping version + CHANGELOG.md
  CHANGELOG.md
  pyproject.toml
Labels: subtensor-localnet:main

#3070 Fix bug with unlocking keypair in mechanism extrinsics
  bittensor/core/extrinsics/asyncex/mechanism.py
  bittensor/core/extrinsics/mechanism.py
  tests/unit_tests/extrinsics/asyncex/test_mechanisms.py
  tests/unit_tests/extrinsics/test_mechanisms.py
Labels: bug

#3072 Release/9.11.1
  CHANGELOG.md
  bittensor/core/extrinsics/asyncex/mechanism.py
  bittensor/core/extrinsics/mechanism.py
  pyproject.toml
  tests/unit_tests/extrinsics/asyncex/test_mechanisms.py
  tests/unit_tests/extrinsics/test_mechanisms.py
Labels: Release

#3076 [v10] `mechid` related changes
  MIGRATION.md
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/metagraph_info.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_metagraph.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: enhancement
