Repository opentensor/bittensor, pull requests merged in 2025-08, with the labels that each got.

#3004 Adds note for installing on macOS
  README.md
Labels: documentation

#3013 Release/9.9.0
  .github/workflows/changelog-checker.yml
  .github/workflows/flake8-and-mypy.yml
  .github/workflows/nightly-e2e-tests-subtensor-main.yml
  .github/workflows/unit-and-integration-tests.yml
  CHANGELOG.md
  README.md
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/dynamic_info.py
  bittensor/core/chain_data/weight_commit_info.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/move_stake.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/move_stake.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/commitments.py
  bittensor/core/subtensor_api/staking.py
  bittensor/core/subtensor_api/subnets.py
  bittensor/core/subtensor_api/utils.py
  bittensor/utils/__init__.py
  bittensor/utils/balance.py
  bittensor/utils/btlogging/loggingmachine.py
  contrib/RELEASE_GUIDELINES.md
  pyproject.toml
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_liquidity.py
  tests/e2e_tests/test_transfer.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/asyncex/test_registration.py
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/test__init__.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_set_weights.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
  tests/unit_tests/utils/test_weight_utils.py
Labels: do not merge, Release, subtensor-localnet:main

#3022 Add async crv4 e2e test
  bittensor/core/async_subtensor.py
  tests/e2e_tests/test_commit_reveal.py
  tests/e2e_tests/utils/chain_interactions.py
Labels: bug, testing

#3025 Fix `flaky` e2e test (tests.e2e_tests.test_staking.test_safe_staking_scenarios)
  tests/e2e_tests/test_staking.py
Labels: bug, testing

#3027 Separation of test modules into separate text elements as independent matrix elements
  .github/workflows/e2e-subtensor-tests.yaml
Labels: testing

#3031 Update changelog + version
  CHANGELOG.md
  pyproject.toml
Labels: subtensor-localnet:main

#3032 Release/9.10.0
  .github/workflows/e2e-subtensor-tests.yaml
  CHANGELOG.md
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/move_stake.py
  bittensor/core/extrinsics/asyncex/registration.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/utils.py
  bittensor/core/extrinsics/move_stake.py
  bittensor/core/extrinsics/registration.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/commitments.py
  bittensor/core/subtensor_api/staking.py
  bittensor/core/subtensor_api/utils.py
  pyproject.toml
  tests/e2e_tests/test_commit_reveal.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_delegate.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_liquidity.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/test_subtensor_functions.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/helpers/__init__.py
  tests/helpers/helpers.py
  tests/unit_tests/extrinsics/asyncex/test_unstaking.py
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/extrinsics/test_unstaking.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
  tests/unit_tests/utils/test_balance.py
Labels: Release, subtensor-localnet:main
