Repository opentensor/bittensor, pull requests merged in 2025-05, with the labels that each got.

#2856 Cleanup, refactoring, small fix, improvement
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  tests/unit_tests/extrinsics/test__init__.py
  tests/unit_tests/extrinsics/test_utils.py
Labels: refactoring

#2857 Add `period` argument to extrinsics calls
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/commit_reveal.py
  bittensor/core/extrinsics/asyncex/move_stake.py
  bittensor/core/extrinsics/asyncex/registration.py
  bittensor/core/extrinsics/asyncex/root.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/start_call.py
  bittensor/core/extrinsics/asyncex/take.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/asyncex/weights.py
  bittensor/core/extrinsics/commit_reveal.py
  bittensor/core/extrinsics/commit_weights.py
  bittensor/core/extrinsics/move_stake.py
  bittensor/core/extrinsics/registration.py
  bittensor/core/extrinsics/root.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/extrinsics/set_weights.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/start_call.py
  bittensor/core/extrinsics/take.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/extrinsics/utils.py
  bittensor/core/subtensor.py
  bittensor/utils/weight_utils.py
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_axon.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_set_subnet_identity_extrinsic.py
  tests/e2e_tests/test_staking.py
  tests/unit_tests/extrinsics/asyncex/test_commit_reveal.py
  tests/unit_tests/extrinsics/asyncex/test_registration.py
  tests/unit_tests/extrinsics/asyncex/test_root.py
  tests/unit_tests/extrinsics/asyncex/test_start_call.py
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/asyncex/test_weights.py
  tests/unit_tests/extrinsics/test_commit_reveal.py
  tests/unit_tests/extrinsics/test_commit_weights.py
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/extrinsics/test_root.py
  tests/unit_tests/extrinsics/test_serving.py
  tests/unit_tests/extrinsics/test_set_weights.py
  tests/unit_tests/extrinsics/test_staking.py
  tests/unit_tests/extrinsics/test_start_call.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/extrinsics/test_unstaking.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
Labels: do not merge, do not review yet

#2858 Add nightly run of e2e tests
  .github/workflows/e2e-subtensor-tests.yaml
Labels: testing

#2859 `period=16` for fast blocks test
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_staking.py
Labels: testing

#2774 Fix some unittests warnings
  tests/unit_tests/extrinsics/test_registration.py
  tests/unit_tests/test_dendrite.py
  tests/unit_tests/test_metagraph.py
  tests/unit_tests/test_subtensor.py
Labels: enhancement, testing

#2862 Introduce `SubtensorApi` interface for SDK
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/__init__.py
  bittensor/core/subtensor_api/chain.py
  bittensor/core/subtensor_api/commitments.py
  bittensor/core/subtensor_api/delegates.py
  bittensor/core/subtensor_api/extrinsics.py
  bittensor/core/subtensor_api/metagraphs.py
  bittensor/core/subtensor_api/neurons.py
  bittensor/core/subtensor_api/queries.py
  bittensor/core/subtensor_api/stakes.py
  bittensor/core/subtensor_api/subnets.py
  bittensor/core/subtensor_api/utils.py
  bittensor/core/subtensor_api/wallets.py
  bittensor/utils/easy_imports.py
  pyproject.toml
  tests/unit_tests/test_subtensor_api.py
Labels: feature, do not merge

#2863 Adds `__all__` to easy_imports.py to get rid of all the #noqa stuff
  bittensor/utils/easy_imports.py
  tests/unit_tests/test_easy_imports.py
Labels: refactoring

#2864 `🥩s` to `staking`
  bittensor/core/subtensor_api/__init__.py
  bittensor/core/subtensor_api/staking.py
  tests/unit_tests/test_subtensor_api.py
Labels: enhancement

#2865 Fix `get_next_epoch_start_block`
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  tests/unit_tests/test_async_subtensor.py
Labels: bug, do not merge

#2875 Add manual way to show the size of virtual environments in the PR
  .github/workflows/monitor_requirements_size_master.yml
Labels: enhancement, show-venv-size

#2878 Improve `Monitor SDK Requirements Size` workflow
  .github/workflows/monitor_requirements_size_master.yml
Labels: enhancement

#2877 Add subtensor.is_subnet_active method
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/subnets.py
  bittensor/core/subtensor_api/utils.py
  tests/e2e_tests/utils/e2e_test_utils.py
  tests/unit_tests/test_subtensor.py
Labels: feature

#2879 Using `hotkey` instead of `coldkey` to sign extrinsic in `serve_axon`
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/serving.py
  tests/unit_tests/test_subtensor.py
Labels: bug

#2880 Rename argument `fallback_chains` to `fallback_endpoints`
  bittensor/core/async_subtensor.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/__init__.py
Labels: enhancement

#2884 Add stake before check `validator_permit`
  tests/e2e_tests/test_root_set_weights.py
Labels: bug

#2886 Add defaults for endpoint and network from local env
  bittensor/core/settings.py
  bittensor/core/types.py
  tests/unit_tests/test_subtensor_api.py
Labels: enhancement

#2888 Improve error message
  bittensor/utils/__init__.py
  tests/unit_tests/extrinsics/test__init__.py
Labels: documentation, enhancement

#2885 Make `unstake` and `unstake_multiple` for all Alphas more clear
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/subtensor.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
Labels: bug, enhancement

#2890 fix publish metadata
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/serving.py
  tests/unit_tests/extrinsics/test_serving.py
Labels: bug

#2892 Release/9.6.1
  CHANGELOG.md
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/core/types.py
  bittensor/utils/__init__.py
  pyproject.toml
  tests/e2e_tests/test_root_set_weights.py
  tests/unit_tests/extrinsics/test__init__.py
  tests/unit_tests/extrinsics/test_serving.py
  tests/unit_tests/test_subtensor.py
  tests/unit_tests/test_subtensor_api.py
  tests/unit_tests/test_subtensor_extended.py
Labels: Release

#2898 e2e workflow: improve skipping logic (no error when skip the job)
  .github/workflows/e2e-subtensor-tests.yaml
Labels: testing

#2900 Replace `transfer_allow_death` with `transfer_keep_alive`
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/subtensor.py
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: enhancement

#2905 Release/9.7.0
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/feature_change.md
  .github/PULL_REQUEST_TEMPLATE/performance_improvement.md
  .github/pull_request_template.md
  .github/workflows/e2e-subtensor-tests.yaml
  CHANGELOG.md
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/transfer.py
  bittensor/core/extrinsics/transfer.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/subnets.py
  bittensor/core/subtensor_api/utils.py
  pyproject.toml
  tests/unit_tests/extrinsics/asyncex/test_transfer.py
  tests/unit_tests/extrinsics/test_transfer.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: Release
