Repository opentensor/bittensor, pull requests merged in 2025-06, with the labels that each got.

#2908 Add local env variable for `config.wallet.*`
  bittensor/core/settings.py
Labels: enhancement

#2911 Release/9.7.1
  CHANGELOG.md
  pyproject.toml
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_staking.py
Labels: Release

#2914 improve `scripts/install.sh`
  scripts/install.sh
Labels: bug, enhancement

#2920 Add `SKIP_PULL` variable for conftest.py
  tests/e2e_tests/conftest.py
Labels: enhancement

#2924 add time for flaky test
  tests/e2e_tests/test_hotkeys.py
Labels: testing

#2925 Add `root_set_pending_childkey_cooldown_extrinsic`
  bittensor/core/async_subtensor.py
  bittensor/core/extrinsics/asyncex/children.py
  bittensor/core/extrinsics/children.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/extrinsics.py
  bittensor/core/subtensor_api/utils.py
  tests/e2e_tests/test_hotkeys.py
  tests/unit_tests/extrinsics/asyncex/test_children.py
  tests/unit_tests/extrinsics/test_children.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor.py
Labels: feature, testing

#2927 New logic for alpha low and high (0.025 <= alpha_low <= alpha_high <= 1)
  tests/e2e_tests/test_liquid_alpha.py
Labels: bug, testing

#2940 decode metadata with empty value
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/utils.py
  tests/unit_tests/chain_data/test_utils.py
Labels: bug

#2876 Reset bonds
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/utils.py
  bittensor/core/extrinsics/asyncex/serving.py
  bittensor/core/extrinsics/serving.py
  bittensor/core/subtensor.py
  bittensor/core/subtensor_api/commitments.py
  bittensor/core/subtensor_api/utils.py
  tests/unit_tests/test_subtensor.py
Labels: feature
