Repository opentensor/bittensor, pull requests merged in 2025-03, with the labels that each got.

#2727 Release/9.0.4
  .github/workflows/e2e-subtensor-tests.yaml
  .github/workflows/release.yml
  CHANGELOG.md
  VERSION
  bittensor/core/async_subtensor.py
  bittensor/core/metagraph.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  bittensor/utils/delegates_details.py
  pyproject.toml
  requirements/prod.txt
  setup.py
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_commit_reveal_v3.py
  tests/e2e_tests/test_commit_weights.py
  tests/e2e_tests/test_delegate.py
  tests/e2e_tests/test_hotkeys.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_metagraph.py
  tests/e2e_tests/test_neuron_certificate.py
  tests/e2e_tests/test_set_weights.py
  tests/e2e_tests/test_staking.py
  tests/e2e_tests/test_subnets.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/helpers/registry
  tests/integration_tests/test_subtensor_integration.py
  tests/unit_tests/extrinsics/test_root.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
Labels: Release

#2736 Feat/safe staking
  bittensor/core/async_subtensor.py
  bittensor/core/chain_data/dynamic_info.py
  bittensor/core/extrinsics/asyncex/move_stake.py
  bittensor/core/extrinsics/asyncex/staking.py
  bittensor/core/extrinsics/asyncex/unstaking.py
  bittensor/core/extrinsics/move_stake.py
  bittensor/core/extrinsics/staking.py
  bittensor/core/extrinsics/unstaking.py
  bittensor/core/subtensor.py
  tests/e2e_tests/test_staking.py
  tests/unit_tests/test_subtensor.py
Labels: feature

#2743 New era of e2e Tests Bittensor
  .github/workflows/e2e-subtensor-tests.yaml
  README.md
  tests/e2e_tests/conftest.py
Labels: do not merge, do not review yet

#2761 Add all supported python versions to e2e tests workflow
  .github/workflows/e2e-subtensor-tests.yaml
Labels: testing

#2760 update docker image name
  tests/e2e_tests/conftest.py
Labels: testing

#2752 Feat: set_children and get_pending_children methods
  bittensor/core/async_subtensor.py
  bittensor/core/errors.py
  bittensor/core/subtensor.py
  bittensor/utils/__init__.py
  bittensor/utils/easy_imports.py
  tests/e2e_tests/test_hotkeys.py
  tests/e2e_tests/utils/chain_interactions.py
  tests/unit_tests/test_async_subtensor.py
  tests/unit_tests/test_subtensor_extended.py
Labels: feature

#2765 Add logic for keep docker image up to date
  .github/workflows/e2e-subtensor-tests.yaml
  tests/e2e_tests/conftest.py
Labels: enhancement

#2769 Fix e2e `conftest.py` for legacy runner
  tests/e2e_tests/conftest.py
Labels: bug, testing

#2780 Fix E2E test_dendrite by making sure Alice is Top validator in Subnet
  tests/e2e_tests/test_dendrite.py
Labels: bug, testing

#2759 Release/9.2.0
  .github/workflows/e2e-subtensor-tests.yaml
  CHANGELOG.md
  README.md
  VERSION
  bittensor/core/async_subtensor.py
  bittensor/core/settings.py
  bittensor/core/subtensor.py
  pyproject.toml
  tests/e2e_tests/conftest.py
  tests/e2e_tests/test_incentive.py
  tests/e2e_tests/test_stake_fee.py
  tests/unit_tests/test_subtensor.py
Labels: Release
